#!/usr/bin/env python
"""
Installation script for dotfiles
"""
import os
import json
from fnmatch import fnmatch


DOTFILES_DIR = os.path.dirname(__file__)
LIST_FILE = os.path.join(DOTFILES_DIR, 'list.json')


def install_dotfiles():
    """Installs the dotfiles by replacing existing ones with (sym)links
    to dotfiles contained within this repository.

    The ``LIST_FILE`` is consulted for any additional options about
    how a particular dotfile has to be handled, i.e. whether it should be
    hardlinked instead of symlinked.
    """
    dotfiles = load_dotfiles_list()

    count = 0
    for dirname, _, files in os.walk(DOTFILES_DIR):
        for filename in files:
            filepath = os.path.join(dirname, filename)
            if not is_dotfile(filepath):
                continue

            install_dotfile(filepath,
                            config=find_dotfile_in_list(dotfiles, filepath))
            count += 1

    print "Installed %d dotfile(s)." % count


def install_dotfile(filepath, config=None):
    """Installs a single dotfile, optionally using the ``config`` for this file
    read from the ``LIST_FILE``.
    :param config: Dictionary of config options
    """
    config = config or {}

    # figure out paths for creating (sym)link from $HOME to dotfiles
    src_dotfile = os.path.abspath(
        os.path.join(DOTFILES_DIR, filepath)
    )
    dest_dotfile = os.path.abspath(
        os.path.expanduser(os.path.join('~', filepath))
    )

    # (re)create the link
    if os.path.exists(dest_dotfile):
        os.unlink(dest_dotfile)
    link_func = os.link if config.get('hardlink') else os.symlink
    link_func(src_dotfile, dest_dotfile)


# Utility functions

def is_dotfile(filepath):
    """Checks if given file in the dotfile repo is indeed an interesting dotfile.
    This very script, for example, is obviously excluded from the category,
    among other files.
    """
    filepath = os.path.relpath(filepath, start=DOTFILES_DIR)
    filepath = os.path.normpath(filepath)

    # TODO: use .gitignore to determine which dotfiles are interesting
    return all([
        filepath.startswith('.'),
        not filepath.startswith('.git'),  # exclude VCS files
        not filepath.endswith('~'),  # exclude backup/temp files
    ])


def load_dotfiles_list():
    """Loads the dotfiles configuration options from ``LIST_FILE``."""
    try:
        with open(LIST_FILE) as f:
            filelist = json.load(f)
    except (IOError, ValueError):
        return {}

    return dict((normalize_path(path), data)
                for path, data in filelist.iteritems())


def find_dotfile_in_list(dotfiles, path):
    """Finds a configuration options for given dotfile in config list."""
    path = normalize_path(path)

    for key, value in dotfiles.iteritems():
        if fnmatch(key, path):
            return value


def normalize_path(path):
    """Unifies given path.

    Letting all paths through this function eliminates some artificial equivalence
    classes between paths, e.g. the ones that only differ by presence of absence
    of initial "./".
    """
    return os.path.normpath(os.path.join('.', path))


if __name__ == '__main__':
    install_dotfiles()
